### ISSUE TITLE
Datamigration only?

### ISSUE THREAD

**Issue by stigfaerch** [dkmedie/fluxmigrate#5]
How high on your list would it be that, apart from data migration, also content types and page layouts are generated?

**Comment by wolffc** [comment]
what does "data migration" contain in your view the question is not clear to me.

in my View a Flux Element containst the following elements:

- Configurtion
   - Fields (TCA)
   - backend Layout
- Template
- Data (Flexform)

so I am not shure what a Data Only conversion should do? put the flexform data in antother flexform?
